---
- hosts: all
  gather_facts: no

  pre_tasks:
  - name: update
    raw: sudo apt-get -y update
  - name: install python
    raw: sudo apt -y  install python

  roles:
    - role: add_user
      vars:
        user_name: gen
  tasks:
    - name: set passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/sudosetup
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        create: yes

    - name: mount fs under chosen user rather than root
      become: yes
      lineinfile:
        path: /etc/fstab
        line: 'LABEL=cheeseboard       /home/gen       ext4    defaults,uid=gen        0 0'
